### ISSUE TITLE
can't run in kibana4.4.1

### ISSUE THREAD

**Issue by pkunico** [chenryn/kbn_sankey_vis#2]
i have run  npm install d3-plugins-sankey
start kibana report fatal error,detail as below:

D:\kibana>D:\kibana\bin\kibana.bat
  log   [00:32:31.236] [fatal] TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (D:\kibana\node_modules\babel-core\lib\transformation\file\options\option-manager.js
    at OptionManager.addConfig (D:\kibana\node_modules\babel-core\lib\transformation\file\options\option-manager.js:10
    at OptionManager.findConfigs (D:\kibana\node_modules\babel-core\lib\transformation\file\options\option-manager.js:
    at OptionManager.init (D:\kibana\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at compile (D:\kibana\node_modules\babel-core\lib\api\register\node.js:117:22)
    at normalLoader (D:\kibana\node_modules\babel-core\lib\api\register\node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (D:\kibana\node_modules\babel-core\lib\api\register\nod
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugins._new$ (D:\kibana\src\server\plugins\PluginCollection.js:57:32)
    at tryCatch (D:\kibana\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\kibana\node_modules\babel-runtime\regenerator\runtime.js:315
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\kibana\node_modules\babel-runtime\regen
    at invoke (D:\kibana\node_modules\babel-runtime\regenerator\runtime.js:136:37)
FATAL [TypeError: Cannot read property 'error' of undefined]

**Comment by JuanCarniglia** [comment]
Ok, I have also run into this, and most commonly it has to do with the node libraries and not the plugin itself. I have solved this googling for the answer, I will try and locate the page I visited with the solution.

**Comment by JuanCarniglia** [comment]
check this [LINK](https://github.com/npm/npm/issues/9766).

Overall, they reccommend a complete removal of node_modules (for this addin!!) and npm install afterwards.

Let me know how this goes.

**Comment by ChristinaLy** [comment]
I met this issue on kibana master dev environment as well. 
@JuanCarniglia With the method you provided, it still not work.

**Comment by ChristinaLy** [comment]
Found another way to workaround the issue:
1. Build a package for this plugin:
    git clone https://github.com/chenryn/kbn_sankey_vis.git
    cd kbn_sankey_vis
    npm install
    gulp package
   
   The package is  kbn_sankey_vis/target/kbn_sankey_vis-0.1.0.tar.gz
2. Install this plugin in package with command:
    ./bin/kibana plugin --install kbn_sankey_vis --url file:///your-directory/kbn_sankey_vis/target/kbn_sankey_vis-0.1.0.tar.gz

**Comment by pkunico** [comment]
When i run "**gulp package**",it report error as below:
D:\git\kbn_sankey_vis>gulp package
[19:12:54] Requiring external module babel-register
[19:12:56] Using gulpfile D:\git\kbn_sankey_vis\gulpfile.babel.js
[19:12:56] Starting 'clean'...
[19:12:56] Finished 'clean' after 12 ms
[19:12:56] Starting 'build'...
[Error: rsync exited with code 1]
[19:12:56] 'build' errored after 133 ms
[19:12:56] Error: rsync exited with code 1
    at Rsync.<anonymous> (D:\git\kbn_sankey_vis\node_modules\rsync\rsync.js:470:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by JuanCarniglia** [comment]
Maybe try installing babel-register first?

**Comment by pkunico** [comment]
I have tried npm install babel-register -g  first,
but it reported the same error

**Comment by pkunico** [comment]
need the d3-plugins-sankey compatible with ECMAScript 6?
the d3-plugins-dist  package seems provide this?

**Comment by ChristinaLy** [comment]
@pkunico Did you try it in Linux? It always show errors when run node.js on Windows.

**Comment by pkunico** [comment]
I have tried it on CentOS6.5 64bit, it still don't work

**Comment by XinCindyChen** [comment]
I encountered the same problem with Kibana 4.3.1 and node 4.3.2, npm 3.8.6 on OSX 10.11.3. Are there any viable solutions to this issue?

**Comment by meenalluktuke** [comment]
Hi,

I use Windows server and facing issue with this plugin on kibana 4.4.1
The steps mentioned above return with error
_C:\Users\simen\Desktop\kbn_sankey_vis>gulp package_
_[11:26:04] Requiring external module babel-register_
_[11:26:13] Using gulpfile ~\Desktop\kbn_sankey_vis\gulpfile.babel.js
[11:26:13] Starting 'clean'...
[11:26:13] Finished 'clean' after 11 ms_
[11:26:13] Starting 'build'...
[Error: rsync exited with code 1]
[11:26:13] 'build' errored after 111 ms
[11:26:13] Error: rsync exited with code 1
    at Rsync.<anonymous> (C:\Users\simen\Desktop\kbn_sankey_vis\node_modules\rsy
nc\rsync.js:470:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)_

and normal method mentioned on the home page give below
_C:\Users\simen\Desktop\kbn_sankey_vis>npm run build

> kbn_sankey_vis@0.1.0 build C:\Users\simen\Desktop\kbn_sankey_vis
> gulp build

[11:38:46] Requiring external module babel-register
[11:38:53] Using gulpfile ~\Desktop\kbn_sankey_vis\gulpfile.babel.js
[11:38:53] Starting 'clean'...
[11:38:53] Finished 'clean' after 20 ms
[11:38:53] Starting 'build'...
[Error: rsync exited with code 1]
[11:38:53] 'build' errored after 23 ms
[11:38:53] Error: rsync exited with code 1
    at Rsync.<anonymous> (C:\Users\simen\Desktop\kbn_sankey_vis\node_modules\
nc\rsync.js:470:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! kbn_sankey_vis@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kbn_sankey_vis@0.1.0 build script 'gulp build'.
npm ERR! This is most likely a problem with the kbn_sankey_vis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project wit
npm ERR!     npm bugs kbn_sankey_vis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls kbn_sankey_vis_

**Comment by JuanCarniglia** [comment]
Finally some progress!

Ok. I downloaded Kibana 4.4.1, and cloned
https://github.com/JuanCarniglia/kbn_sankey_vis.git (which is a fork, that
is as of now identical to the original from chenryn).

Then:

npm install

Then:

npm run build

At this time, I got _your exact error message_.

After debugging the build process, with this line

node "c:\Program
Files\nodejs\node_modules\node-inspector\bin\node-debug.js" --no-preload
--debug-brk node_modules\gulp\bin\gulp.js build

I found out that rsync.js is a wrapper class to execute the command
rsync.exe, which\* I didn't have on my windows box*.

So, I downloaded it from https://www.itefix.net/cwrsync.

After I installed it, I had to add the PATH reference to the binary:

set path=%PATH%;[Where in the world you installed rsyn]\bin

_(Remember to add this to the GLOBAL setttings, otherwise you only have
this on your running CMD context)_

All that got me somewhere closer but not just there. After a lot of
research, I found out that when rsync.js, executes the actual command (with
shell), _there is an issue with the absolute paths_. In the command, there
is a source and destination parameter. If those parameters are like
"c:\blah\blah\blah", rsync fails with a message saying that "both the
source and destination cannot be remote" WTF?

You can check it running this from command line (from the plugin dir):

node node_modules\rsync\rsync.js -uavr --delete --include=package.json
--include=index.js --include=node_modules --include=public
--exclude="node_modules\babel-eslint" --exclude="node_modules\bluebird"
--exclude="node_modules\bower" --exclude="node_modules\del"
--exclude="node_modules\eslint"
--exclude="node_modules\eslint-plugin-mocha"
--exclude="node_modules\gulp" --exclude="node_modules\gulp-eslint"
--exclude="node_modules\gulp-gzip" --exclude="node_modules\gulp-tar"
--exclude="node_modules\gulp-util" --exclude="node_modules\gulp-zip"
--exclude="node_modules\husky" --exclude="node_modules\lodash"
--exclude="node_modules\minimist" --exclude="node_modules\mkdirp"
--exclude="node_modules\rimraf" --exclude="node_modules\rsync" "
_C:\Users\myUser\kibana\kibana-4.4.1-test\clean\src\plugins\kbn_sankey_vis\package.json_"
"
_C:\Users\myUser\kibana\kibana-4.4.1-test\clean\src\plugins\kbn_sankey_vis\build\kbn_sankey_vis-0.1.0_
"

So, I edited the gulpfile.babel.js so that the destination looks like "
_build/kbn_sankey_vis_" and the source just "_._" (remember, you have
to be on the plugin folder).

(I attach my gulpfile.babel.js file, so that you can compare, and I am
editing my README page and so on.)

Then It started to copy all files into the build. BUT.

I smacked right into the MAX_LENGTH (260) for file paths limitation in NTFS.

So, instead of running "cp -r source origin" or xcopy, I winded out using
ROBOCOPY, which ships by default with Windows 7 (at least).

robocopy build\kbn_sankey_vis "
_C:\Users\myUser\kibana\kibana-4.4.1-test\clean\_
installedPlugins\kbn_sankey_vis"

It took forever+1, but at last it worked.

This is something WINDOWS related. In Linux(es), there would be rsync
installed by default, and your paths would all look differently.

Let me know how it goes.

2016-04-20 8:40 GMT-03:00 meenalluktuke notifications@github.com:

> Hi,
> 
> I use Windows server and facing issue with this plugin on kibana 4.4.1
> The steps mentioned above return with error
> _C:\Users\simen\Desktop\kbn_sankey_vis>gulp package
> 
> [11:26:04] Requiring external module babel-register
> [11:26:13] Using gulpfile ~\Desktop\kbn_sankey_vis\gulpfile.babel.js
> [11:26:13] Starting 'clean'...
> [11:26:13] Finished 'clean' after 11 ms
> [11:26:13] Starting 'build'...
> [Error: rsync exited with code 1]
> [11:26:13] 'build' errored after 111 ms
> [11:26:13] Error: rsync exited with code 1
> at Rsync. (C:\Users\simen\Desktop\kbn_sankey_vis\node_modules\rsy
> nc\rsync.js:470:21)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:827:16)
> at Socket. (internal/child_process.js:319:11)
> at emitOne (events.js:77:13)
> at Socket.emit (events.js:169:7)
> at Pipe._onclose (net.js:477:12)_
> 
> and normal method mentioned on the home page give below
> _C:\Users\simen\Desktop\kbn_sankey_vis>npm run build
> 
> kbn_sankey_vis@0.1.0 build C:\Users\simen\Desktop\kbn_sankey_vis
> gulp build
> 
> [11:38:46] Requiring external module babel-register
> [11:38:53] Using gulpfile ~\Desktop\kbn_sankey_vis\gulpfile.babel.js
> [11:38:53] Starting 'clean'...
> [11:38:53] Finished 'clean' after 20 ms
> [11:38:53] Starting 'build'...
> [Error: rsync exited with code 1]
> [11:38:53] 'build' errored after 23 ms
> [11:38:53] Error: rsync exited with code 1
> at Rsync. (C:\Users\simen\Desktop\kbn_sankey_vis\node_modules\
> nc\rsync.js:470:21)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:827:16)
> at Socket. (internal/child_process.js:319:11)
> at emitOne (events.js:77:13)
> at Socket.emit (events.js:169:7)
> at Pipe._onclose (net.js:477:12)
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
> node_modules\npm\bin\npm-cli.js" "run" "build"
> npm ERR! node v4.4.3
> npm ERR! npm v2.15.1
> npm ERR! code ELIFECYCLE
> npm ERR! kbn_sankey_vis@0.1.0 build: gulp build
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the kbn_sankey_vis@0.1.0 build script 'gulp build'.
> npm ERR! This is most likely a problem with the kbn_sankey_vis package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! gulp build
> npm ERR! You can get information on how to open an issue for this project
> wit
> npm ERR! npm bugs kbn_sankey_vis
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR! npm owner ls kbn_sankey_vis_
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/chenryn/kbn_sankey_vis/issues/2#issuecomment-212391891

## 

Juan Ignacio Carniglia

**Comment by meenalluktuke** [comment]
@JuanCarniglia  

I tried all the steps you gave above
1) Cloned your git repository
2) npm install
3) npm run build
No error till here, all went well
using robocopy, i copied the folder into $KIBANA_HOME/installedplugins.

Then started kibana, but got below error

C:\kibana-4.5.0-windows\kibana-4.5.0-windows\bin>kibana.bat
  log   [15:05:12.438] [fatal] TypeError: Cannot read property 'error' of undefi
ned
    at OptionManager.mergeOptions (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\
node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:28
)
    at OptionManager.addConfig (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\nod
e_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\n
ode_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)

```
at OptionManager.init (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_mod
```

ules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at compile (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel-
core\lib\api\register\node.js:117:22)
    at normalLoader (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\b
abel-core\lib\api\register\node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js](C:kibana-4.5.0-
windowskibana-4.5.0-windowsnode_modulesbabel-corelibapiregisternode.js:21
6:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugins._new$ (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\src\server\pl
ugins\PluginCollection.js:57:32)
    at tryCatch (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel
-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](C:kibana-4.5.0-windowsk
ibana-4.5.0-windowsnode_modulesbabel-runtimeregeneratorruntime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](C:k
ibana-4.5.0-windowskibana-4.5.0-windowsnode_modulesbabel-runtimeregenerator
runtime.js:100:21)
    at invoke (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel-r
untime\regenerator\runtime.js:136:37)
FATAL [TypeError: Cannot read property 'error' of undefined]

**Comment by JuanCarniglia** [comment]
Try removing the .babelrc file.

2016-04-25 10:08 GMT-03:00 meenalluktuke notifications@github.com:

> @JuanCarniglia https://github.com/JuanCarniglia
> 
> I tried all the steps you gave above
> 1) Cloned your git repository
> 2) npm install
> 3) npm run build
> No error till here, all went well
> using robocopy, i copied the folder into $KIBANA_HOME/installedplugins.
> 
> Then started kibana, but got below error
> 
> C:\kibana-4.5.0-windows\kibana-4.5.0-windows\bin>kibana.bat
> log [15:05:12.438] [fatal] TypeError: Cannot read property 'error' of
> undefi
> ned
> at OptionManager.mergeOptions
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\
> 
> node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:28
> )
> at OptionManager.addConfig
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\nod
> 
> e_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
> at OptionManager.findConfigs
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\n
> 
> ode_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
> 
> at OptionManager.init (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_mod
> 
> ules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
> at compile
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel-
> core\lib\api\register\node.js:117:22)
> at normalLoader
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\b
> abel-core\lib\api\register\node.js:199:14)
> at Object.require.extensions.(anonymous function) as .js
> at Module.load (module.js:343:32)
> at Function.Module._load (module.js:300:12)
> at Module.require (module.js:353:17)
> at require (internal/module.js:12:17)
> at Plugins._new$
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\src\server\pl
> ugins\PluginCollection.js:57:32)
> at tryCatch
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel
> -runtime\regenerator\runtime.js:67:40)
> at GeneratorFunctionPrototype.invoke as _invoke
> at GeneratorFunctionPrototype.prototype.(anonymous function) as next
> at invoke
> (C:\kibana-4.5.0-windows\kibana-4.5.0-windows\node_modules\babel-r
> untime\regenerator\runtime.js:136:37)
> FATAL [TypeError: Cannot read property 'error' of undefined]
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/chenryn/kbn_sankey_vis/issues/2#issuecomment-214310205

## 

Juan Ignacio Carniglia

**Comment by meenalluktuke** [comment]
It works, thank you!

**Comment by chenryn** [comment]
thanks for @JuanCarniglia , there is a stupid typo in `gulpfile.babel.js`: https://github.com/chenryn/kbn_sankey_vis/commit/0a3a62d164af0af6b17efa21e04b478c8bad80a6
