### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by pkunico** [chenryn/kbn_sankey_vis#3]
when run the command 'npm run build'  ,it report error,detail as below:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! kbn_sankey_vis@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kbn_sankey_vis@0.1.0 build script 'gulp build'.
npm ERR! This is most likely a problem with the kbn_sankey_vis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls kbn_sankey_vis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\git\kbn_sankey_vis\npm-debug.log

**Comment by JuanCarniglia** [comment]
Do you have GULP correctly installed? can you run : 

`"D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"`

On the plugin folder, and let us know what it yields?

Thanks!

**Comment by pkunico** [comment]
Thanks!
it yields the same error

**Comment by JuanCarniglia** [comment]
I just run...

`git clone https://github.com/chenryn/kbn_sankey_vis`

`npm install --loglevel=silly`

`npm build --loglevel=silly`

`npm run --loglevel=silly`

It all worked fine. Try the loglevel setting to see if it yields more information.

**Comment by pkunico** [comment]
I just try the loglevel setting,It all worked fine! Thanks~~
