### ISSUE TITLE
IP address and Timestamp wrongly formatted

### ISSUE THREAD

**Issue by dando-it** [chenryn/kbn_sankey_vis#5]
I succesfully installed the plugin on a kibana 4.4.2 environment (along with Timelion plugin).

The only issue found is the wrong formatting of **IP** and **Timestamp** field data (they appear in the native _LONG_ integer data type).
All the existing visualizations (pie, bar, etc..)  are working correctly.
Any hint ?
Thanks

![sankey_formatting_1](https://cloud.githubusercontent.com/assets/9216902/15046505/510b7486-12e0-11e6-9482-912d221f28c7.jpg)

**Comment by JuanCarniglia** [comment]
Just one Hint, I would never use a timestamp in a Sankey chart. It would
yield too many elements. Maybe you can come up with a scripted field (For
instance, "Week-Month") something that would generate a smaller aggregation
(less buckets).

Other than that, I guess that all the other vis make some kind of
transformation on those fields, and this particular vis does not (for sure)
transform anything.

2016-05-05 11:44 GMT-03:00 dando-it notifications@github.com:

> I succesfully installed the plugin on a kibana 4.4.2 environment (along
> with Timelion plugin).
> 
> The only issue found is the wrong formatting of _IP_ and _Timestamp_
> field data (they appear in the native _LONG_ integer data type).
> All the existing visualizations (pie, bar, etc..) are working correctly.
> Any hint ?
> Thanks
> 
> [image: sankey_formatting_1]
> https://cloud.githubusercontent.com/assets/9216902/15046505/510b7486-12e0-11e6-9482-912d221f28c7.jpg
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/chenryn/kbn_sankey_vis/issues/5

## 

Juan Ignacio Carniglia

**Comment by dando-it** [comment]
Juan, i use the Date Histogram  aggregation as first bucket (with custom intervals to keep the slices within a readable number) to get the temporal relations between the other buckets.

I agree with you that this visualization needs to be aware of the specific formatting for the IP type (usually IPs are stored as strings), but seems odd that also the Timestamp isn't recognized.

**Comment by chenryn** [comment]
yes, I check the offical vis and use `agg.fieldFormatter()` now: https://github.com/chenryn/kbn_sankey_vis/commit/271e5f5aa02b9fad8e98292b3ad1439bd09db02c
