### ISSUE TITLE
Install Offline

### ISSUE THREAD

**Issue by userBD** [chenryn/kbn_sankey_vis#8]
Hi,

Is there a way to make an offline install on red hat plz ?

Thx all.

**Comment by JuanCarniglia** [comment]
What do you mean? You can download a zip with all the files and just unzip
IT at "src/plugins/kbn_sankey_vis", then you would have to remove the
optimized bundle file (optimize/bundles/kibana.bundle.is), a d run kibana
again.

**Comment by userBD** [comment]
Sorry i'm late.

So i try, but the file downloaded is "kbn_sankey_vis-master", maybe it's nothing, i don't know, but it makes me think that it needs something before install.

And the try failed, with the error : 

```
ERROR in ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis.js
    Module build failed: ReferenceError: [BABEL] /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public/kbn_sankey_vis.js: Unknown option: /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/.babelrc.presets
        at Logger.error (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
        at OptionManager.mergeOptions (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
        at OptionManager.addConfig (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
        at OptionManager.findConfigs (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
        at OptionManager.init (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
        at File.initOptions (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/index.js:147:75)
        at new File (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/index.js:137:22)
        at Pipeline.transform (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
        at transpile (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-loader/index.js:12:22)
        at Object.module.exports (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-loader/index.js:69:12)
     @ ./optimize/bundles/kibana.entry.js 127:0-48
```

Maybe now it's a BABEL problem ?

**Comment by JuanCarniglia** [comment]
Ok, try and remove the .babel.rc file.

2016-05-19 10:57 GMT-03:00 userBD notifications@github.com:

> Sorry i'm late.
> 
> So i try, but the file downloaded is "kbn_sankey_vis-master", maybe it's
> nothing, i don't know, but it makes me think that it needs something before
> install.
> 
> And the try failed, with the error :
> 
> ERROR in ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis.js
>     Module build failed: ReferenceError: [BABEL] /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public/kbn_sankey_vis.js: Unknown option: /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/.babelrc.presets
>         at Logger.error (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
>         at OptionManager.mergeOptions (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
>         at OptionManager.addConfig (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
>         at OptionManager.findConfigs (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
>         at OptionManager.init (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
>         at File.initOptions (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/index.js:147:75)
>         at new File (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/file/index.js:137:22)
>         at Pipeline.transform (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
>         at transpile (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-loader/index.js:12:22)
>         at Object.module.exports (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/babel-loader/index.js:69:12)
>      @ ./optimize/bundles/kibana.entry.js 127:0-48
> 
> Maybe now it's a BABEL problem ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/chenryn/kbn_sankey_vis/issues/8#issuecomment-220332094

## 

Juan Ignacio Carniglia

**Comment by userBD** [comment]
i made all the action before the first launch and i have the error :

>   log   [10:53:14.925] [info][optimize] Optimizing and caching bundles for kibana and statusPage. This may take a few minutes
>   log   [10:54:20.378] [fatal] Error: Optimizations failure.
> 
> ```
> ERROR in ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js
> Module not found: Error: Cannot resolve module 'd3-plugins-sankey' in /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public
>  @ ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js 6:0-28 16:10-38
> 
> at Object.exports.create (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/boom/lib/index.js:21:17)
> at FsOptimizer.failedStatsToError (/usr/elk/kibana/kibana-4.3.1-linux-x64/src/optimize/BaseOptimizer.js:189:19)
> at /usr/elk/kibana/kibana-4.3.1-linux-x64/src/optimize/FsOptimizer.js:72:35
> at Compiler.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compiler.js:181:13)
> at /usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compiler.js:403:12
> at Compiler.next (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
> at Compiler.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/CachePlugin.js:40:4)
> at Compiler.applyPluginsAsync (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
> at Compiler.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compiler.js:400:9)
> at Compilation.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compilation.js:576:13)
> at Compilation.applyPluginsAsync (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
> at Compilation.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compilation.js:571:10)
> at Compilation.applyPluginsAsync (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
> at Compilation.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/lib/Compilation.js:566:9)
> at Compilation.next (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
> at ExtractTextPlugin.<anonymous> (/usr/elk/kibana/kibana-4.3.1-linux-x64/node_modules/extract-text-webpack-plugin/index.js:303:4)
> ```
> 
> FATAL { [Error: Optimizations failure.
> 
> ```
> ERROR in ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js
> Module not found: Error: Cannot resolve module 'd3-plugins-sankey' in /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public
>  @ ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js 6:0-28 16:10-38
> ```
> 
> ]
>   cause:
>    { [Error: Optimizations failure.
> 
> ```
>    ERROR in ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js
>    Module not found: Error: Cannot resolve module 'd3-plugins-sankey' in /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public
>     @ ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js 6:0-28 16:10-38
> ```
> 
>    ]
>      data: { errors: [Object], warnings: [], publicPath: '/bundles/' },
>      isBoom: true,
>      isServer: true,
>      output: { statusCode: 500, payload: [Object], headers: {} },
>      reformat: [Function] },
>   isOperational: true,
>   data:
>    { errors: [ './src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js\nModule not found: Error: Cannot resolve module \'d3-plugins-sankey\' in /usr/elk/kibana/kibana-4.3.1-linux-x64/src/plugins/kbn_sankey_vis/public\n @ ./src/plugins/kbn_sankey_vis/public/kbn_sankey_vis_controller.js 6:0-28 16:10-38' ],
>      warnings: [],
>      publicPath: '/bundles/' },
>   isBoom: true,
>   isServer: true,
>   output:
>    { statusCode: 500,
>      payload:
>       { statusCode: 500,
>         error: 'Internal Server Error',
>         message: 'An internal server error occurred' },
>      headers: {} },
>   reformat: [Function] }

**Comment by JuanCarniglia** [comment]
You are missing the d3-plugin-sankey js... Hace you run npm install on the
vis directory?

**Comment by userBD** [comment]
No i don't have npm and i'm offline :(

**Comment by JuanCarniglia** [comment]
You have to figure some way to run npm install on the kbn_sankey_vis folder. 

Anyway, here is the node_module you are missing, see if you can uncompress it on the kbn_sankey_vis/node_modules folder.

[d3-plugins-sankey.zip](https://github.com/chenryn/kbn_sankey_vis/files/276547/d3-plugins-sankey.zip)

Good luck!

**Comment by JuanCarniglia** [comment]
Any progress? Do you want me to send you a zip file with the node
components?
El may. 20, 2016 6:39, "userBD" notifications@github.com escribió:

No i don't have npm and i'm offline :(

**Comment by userBD** [comment]
Yes, it works.

I used an online computers for npm then i took the file and put on the offline one.

And it's ok, sry not to say it before.
