### ISSUE TITLE
Compatibility with Kibana5

### ISSUE THREAD

**Issue by dxl2** [chenryn/kbn_sankey_vis#9]
Are there any plans to make this compatible with Kibana 5? I get this error when trying to render the visualization: 
TypeError: handlerTypes[chartType] is not a function

**Comment by chenryn** [comment]
well, I had a try months ago but failed: https://github.com/chenryn/kbn_sankey_vis/issues/6

---

You can see the branch at: https://github.com/chenryn/kbn_sankey_vis/tree/kibana5

**Comment by chenryn** [comment]
done by https://github.com/chenryn/kbn_sankey_vis/commit/f3c2ba419069026aad8332920f3159dada3a42af
